output = "internal/models"
wipe = true
no-tests = true

[psql]
  dbname = "go_slack_unipos_development"
  host = "localhost"
  port = 5432
  user = "postgres"
  pass = "postgres"
  blacklist = ["schema_migrations"]
  sslmode = "disable"
